from django.urls import path
from main.views import (IndexView, DepartmentListView, DepartmentDetailView,
    DepartmentCreateView, DepartmentDeleteView, DepartmentUpdateView,
    CourseDetailView, CourseCreateView, CourseUpdateView, CourseDeleteView,
    GroupDetailView, GroupCreateView, GroupUpdateView, GroupDeleteView, 
    ModuleDetailView, ModuleCreateView, ModuleDeleteView, ModuleUpdateView,
    ExamDetailView, ExamUpdateView, ExamDeleteView, ExamCreateView,
    ExamDetailView, GradeCreateView, GradeUpdateView, GradeDeleteView,
    restore_db)

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('restore-db/', restore_db, name='restore_db'),
    path('departments/', DepartmentListView.as_view(), name='departments'),
    path('departments/add/', DepartmentCreateView.as_view(), name='add_department'),
    path('departments/<slug:slug>/', DepartmentDetailView.as_view(), name='department'),
    path('departments/<slug:slug>/edit/', DepartmentUpdateView.as_view(), name='edit_department'),
    path('departments/<slug:slug>/delete/', DepartmentDeleteView.as_view(), name='delete_department'),
    path('departments/<slug:slug>/add_course/', CourseCreateView.as_view(), name='add_course'),
    path('courses/<slug:slug>/', CourseDetailView.as_view(), name='course'),
    path('courses/<slug:slug>/edit/', CourseUpdateView.as_view(), name='edit_course'),
    path('courses/<slug:slug>/delete/', CourseDeleteView.as_view(), name='delete_course'),
    path('courses/<slug:slug>/add_group/', GroupCreateView.as_view(), name='add_group'),
    path('courses/<slug:slug>/add_module/', ModuleCreateView.as_view(), name='add_module'),
    path('groups/<int:pk>/', GroupDetailView.as_view(), name='group'),
    path('groups/<int:pk>/edit/', GroupUpdateView.as_view(), name='edit_group'),
    path('groups/<int:pk>/delete/', GroupDeleteView.as_view(), name='delete_group'),
    path('modules/<int:pk>/', ModuleDetailView.as_view(), name='module'),
    path('modules/<int:pk>/edit/', ModuleUpdateView.as_view(), name='edit_module'),
    path('modules/<int:pk>/delete/', ModuleDeleteView.as_view(), name='delete_module'),
    path('modules/<int:pk>/add-exam/', ExamCreateView.as_view(), name='add_exam'),
    path('exams/<int:pk>/', ExamDetailView.as_view(), name='exam'),
    path('exams/<int:pk>/edit/', ExamUpdateView.as_view(), name='edit_exam'),
    path('exams/<int:pk>/delete/', ExamDeleteView.as_view(), name='delete_exam'),
    path('exams/<int:pk>/add-grade/', GradeCreateView.as_view(), name='add_grade'),
    path('grades/<int:pk>/edit/', GradeUpdateView.as_view(), name='edit_grade'),
    path('grades/<int:pk>/delete/', GradeDeleteView.as_view(), name='delete_grade'),
]